import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

import type { Metadata } from "next";
import "../globals.css";
import { Poppins } from "next/font/google";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import EmojiRain from "@/components/EmojiRain";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Moodflix By Carlos Bolaño",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/icon.png",
        type: "image/png",
      },
    ],
  },
};
export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={poppins.className}>
        <NextIntlClientProvider messages={messages}>
          <div className="relative min-h-screen justify-between flex flex-col ">
            <Navbar />
            <main className="pt-8 md:pt-20 container mx-auto px-2">{children}</main>
            <Footer />
            <EmojiRain />
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
